refactor: set card info by card number
juntz/ZtmyCard pull request #28
Opened 2024-08-14 14:49 UTC by juntz

2024-08-29 03:03 UTC, ffdd270 commented on scripts/card.gd
> +func _set_info(info):
중요사항은 아니지만 코멘트 해두면 나중에 작업하실 때 도움 될 것 같아 남겨놓습니다. godot에서 private로 취급하는 멤버변수들은 var _name 이렇게 사용하고 있더라고요. 파라미터 이름과 곂치지 않게 함과 동시에 GDScript에서는 접근을 제어하는 키워드가 없어서 프로그래머가 눈치것 이름보고 피하게 시키는데. 차후 private들에는 _가 적용되면 좋지 않을까... 라는 의견 드립니다.

2024-08-29 03:09 UTC, ffdd270 requested changes
_static_init 부분만 확인 부탁드립니다! \(__ ) 항상 작업해주셔서 감사합니다!

2024-08-29 03:09 UTC, ffdd270 commented on scripts/card.gd
> +static func _static_init():
_static_init의 호출을 하는 게 아무도 없어서 card_info가 항상 {}일 것 같습니다.

2024-08-29 13:58 UTC, juntz commented on scripts/card.gd
> +static func _static_init():
_static_init 메서드는 _ready 처럼 시스템에서 자동으로 호출합니다!
참고: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#static-constructor

2024-09-01 11:03 UTC, ffdd270 commented on scripts/card.gd
> +static func _static_init():
헉 알려주셔서 감사합니다! 'ㅁ 'bb 예약된 함수였군요...!

2024-09-01 11:03 UTC, merged